# Generated by Django 5.2 on 2025-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geohash',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
