# Generated by Django 5.2 on 2025-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_geohash'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='precision',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=6),
        ),
    ]
