# Generated by Django 5.2 on 2025-05-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=17, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, default='#b1019f', max_length=7, null=True),
        ),
    ]
