# Generated by Django 5.2 on 2025-05-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone_alter_user_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, default='#6d17b2', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar/'),
        ),
    ]
