# Generated by Django 5.2 on 2025-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_color_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, default='#4b7b74', max_length=7, null=True),
        ),
    ]
