# Generated by Django 5.2 on 2025-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(blank=True, default='#1da85a', max_length=7, null=True),
        ),
    ]
