# Generated by Django 5.2 on 2025-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(blank=True, to='directory.category'),
        ),
    ]
